

name: 'Analysis'
version: '1.0.0'
config-version: 2

profile: 'default'
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

models:
  my_new_project:
    staging:           # <-- folder: models/staging
      +schema: staging
      +materialized: view

    intermediate:      # <-- folder: models/intermediate
      +schema: intermediate
      +materialized: view

    Marts:             # <-- capital M to match models/Marts
      +schema: marts
      +materialized: table

    # ❌ Remove this if you don't have models/example/*
    # example:
    #   +schema: example