name: 'retail_analytics'
version: '1.0.0'
config-version: 2

profile: 'retail_analytics'   # must exist in your ~/.dbt/profiles.yml

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

models:
  retail_analytics:
    +materialized: view

    staging:
      +materialized: view
      +tags: ['staging']

    intermediate:
      +materialized: view
      +tags: ['intermediate']

    marts:
      +materialized: table
      +tags: ['marts']