version: 2

models:
  - name: stg_orders
    columns:
      - name: sales_order_line_key
        tests: [not_null, unique]

      - name: customer_key
        tests:
          - relationships:
              arguments:
                to: ref('stg_customerdata')
                field: customer_key
              config: {severity: warn}

      - name: product_key
        tests:
          - relationships:
              arguments:
                to: ref('stg_productdata')
                field: product_key
              config: {severity: warn}